// Data de contenido por módulo para el panel lateral
import { ModuleContent } from '../types/module-content';

export const moduleContentMap: Record<string, ModuleContent> = {
  // SIGA real
    SIGA: {
      problem: 'Gestión y trazabilidad de inspecciones operativas en campo.',
      system: 'SIGA (Sistema Integral de Gestión de Auditorías)',
      capabilities: ['Trazabilidad', 'Automatización', 'Reportes', 'Integración GIS'],
      result: 'Reducción de tiempos de inspección y mejora en la calidad de datos operativos.',
      deployedIn: 'Navarro Competición',
      connectedModules: [
        { name: 'OVT Platform', type: 'Core' },
        { name: 'Analytics Core', type: 'Data' },
      ],
      visualLabel: 'SIGA',
      type: 'SIGA',
      title: 'SIGA',
      index: 'SIGA'
    },
  // Placeholders para los 32 módulos
  'Systems Architecture': {
    problem: 'Definición estructural de sistemas y procesos.',
    system: 'Systems Architecture',
    capabilities: ['Estructura', 'Documentación', 'Metodología'],
    result: 'Base para integración y escalabilidad.',
    connectedModules: [],
    visualLabel: 'Architecture',
    type: 'placeholder',
    title: 'Systems Architecture',
    index: 1,
  },
  'OVT Platform': {
    problem: 'Plataforma operativa centralizada.',
    system: 'OVT Platform',
    capabilities: ['Integración', 'Automatización'],
    result: 'Operación unificada.',
    connectedModules: [],
    visualLabel: 'OVT',
    type: 'placeholder',
    title: 'OVT Platform',
    index: 2,
  },
  'Analytics Core': {
    problem: 'Procesamiento y análisis de datos operativos.',
    system: 'Analytics Core',
    capabilities: ['Data', 'Reporting'],
    result: 'Insights accionables.',
    connectedModules: [],
    visualLabel: 'Analytics',
    type: 'placeholder',
    title: 'Analytics Core',
    index: 3,
  },
  'Experience Portal': {
    problem: 'Interfaz de usuario para experiencias.',
    system: 'Experience Portal',
    capabilities: ['UX', 'Acceso'],
    result: 'Experiencia centralizada.',
    connectedModules: [],
    visualLabel: 'Portal',
    type: 'placeholder',
    title: 'Experience Portal',
    index: 4,
  },
  'Automation Layer': {
    problem: 'Automatización de procesos operativos.',
    system: 'Automation Layer',
    capabilities: ['Automatización'],
    result: 'Procesos eficientes.',
    connectedModules: [],
    visualLabel: 'Automation',
    type: 'placeholder',
    title: 'Automation Layer',
    index: 5,
  },
  'Operational Dashboard': {
    problem: 'Visualización de operaciones en tiempo real.',
    system: 'Operational Dashboard',
    capabilities: ['Visualización', 'Monitoreo'],
    result: 'Control operativo.',
    connectedModules: [],
    visualLabel: 'Dashboard',
    type: 'placeholder',
    title: 'Operational Dashboard',
    index: 6,
  },
  'Data Pipelines': {
    problem: 'Flujo y transformación de datos.',
    system: 'Data Pipelines',
    capabilities: ['ETL', 'Integración'],
    result: 'Datos limpios.',
    connectedModules: [],
    visualLabel: 'Pipelines',
    type: 'placeholder',
    title: 'Data Pipelines',
    index: 7,
  },
  'Realtime Monitoring': {
    problem: 'Monitoreo en tiempo real.',
    system: 'Realtime Monitoring',
    capabilities: ['Monitoreo', 'Alertas'],
    result: 'Detección temprana.',
    connectedModules: [],
    visualLabel: 'Monitoring',
    type: 'placeholder',
    title: 'Realtime Monitoring',
    index: 8,
  },
  'System Integrations': {
    problem: 'Integración de sistemas externos.',
    system: 'System Integrations',
    capabilities: ['Integración'],
    result: 'Conectividad ampliada.',
    connectedModules: [],
    visualLabel: 'Integrations',
    type: 'placeholder',
    title: 'System Integrations',
    index: 9,
  },
  'Operational UX': {
    problem: 'Experiencia de usuario en operaciones.',
    system: 'Operational UX',
    capabilities: ['UX'],
    result: 'Interacción optimizada.',
    connectedModules: [],
    visualLabel: 'UX',
    type: 'placeholder',
    title: 'Operational UX',
    index: 10,
  },
  'Automation Workflows': {
    problem: 'Automatización de flujos de trabajo.',
    system: 'Automation Workflows',
    capabilities: ['Automatización'],
    result: 'Flujos eficientes.',
    connectedModules: [],
    visualLabel: 'Workflows',
    type: 'placeholder',
    title: 'Automation Workflows',
    index: 11,
  },
  'GIS Interfaces': {
    problem: 'Interfaz para sistemas GIS.',
    system: 'GIS Interfaces',
    capabilities: ['GIS'],
    result: 'Integración geoespacial.',
    connectedModules: [],
    visualLabel: 'GIS',
    type: 'placeholder',
    title: 'GIS Interfaces',
    index: 12,
  },
  'Service Platforms': {
    problem: 'Plataformas de servicios.',
    system: 'Service Platforms',
    capabilities: ['Servicios'],
    result: 'Oferta ampliada.',
    connectedModules: [],
    visualLabel: 'Services',
    type: 'placeholder',
    title: 'Service Platforms',
    index: 13,
  },
  'API Systems': {
    problem: 'Sistemas de APIs.',
    system: 'API Systems',
    capabilities: ['API'],
    result: 'Interoperabilidad.',
    connectedModules: [],
    visualLabel: 'API',
    type: 'placeholder',
    title: 'API Systems',
    index: 14,
  },
  'Data Visualization': {
    problem: 'Visualización avanzada de datos.',
    system: 'Data Visualization',
    capabilities: ['Visualización'],
    result: 'Datos comprensibles.',
    connectedModules: [],
    visualLabel: 'Viz',
    type: 'placeholder',
    title: 'Data Visualization',
    index: 15,
  },
  'Infrastructure Design': {
    problem: 'Diseño de infraestructura.',
    system: 'Infrastructure Design',
    capabilities: ['Infraestructura'],
    result: 'Base robusta.',
    connectedModules: [],
    visualLabel: 'Infra',
    type: 'placeholder',
    title: 'Infrastructure Design',
    index: 16,
  },
  'Agency Site': {
    problem: 'Sitio web institucional.',
    system: 'Agency Site',
    capabilities: ['Web'],
    result: 'Presencia digital.',
    connectedModules: [],
    visualLabel: 'Site',
    type: 'placeholder',
    title: 'Agency Site',
    index: 17,
  },
  'Commerce Front': {
    problem: 'Front-end de comercio.',
    system: 'Commerce Front',
    capabilities: ['E-commerce'],
    result: 'Ventas online.',
    connectedModules: [],
    visualLabel: 'Commerce',
    type: 'placeholder',
    title: 'Commerce Front',
    index: 18,
  },
  'Inspection System': {
    problem: 'Sistema de inspección.',
    system: 'Inspection System',
    capabilities: ['Inspección'],
    result: 'Control de calidad.',
    connectedModules: [],
    visualLabel: 'Inspection',
    type: 'placeholder',
    title: 'Inspection System',
    index: 19,
  },
  'Service Tracker': {
    problem: 'Seguimiento de servicios.',
    system: 'Service Tracker',
    capabilities: ['Tracking'],
    result: 'Servicios controlados.',
    connectedModules: [],
    visualLabel: 'Tracker',
    type: 'placeholder',
    title: 'Service Tracker',
    index: 20,
  },
  'Ops Logbook': {
    problem: 'Registro de operaciones.',
    system: 'Ops Logbook',
    capabilities: ['Registro'],
    result: 'Historial operativo.',
    connectedModules: [],
    visualLabel: 'Logbook',
    type: 'placeholder',
    title: 'Ops Logbook',
    index: 21,
  },
  'Navarro Platform': {
    problem: 'Plataforma de servicios Navarro.',
    system: 'Navarro Platform',
    capabilities: ['Servicios'],
    result: 'Integración local.',
    connectedModules: [],
    visualLabel: 'Navarro',
    type: 'placeholder',
    title: 'Navarro Platform',
    index: 22,
  },
  'Experience System': {
    problem: 'Sistema de experiencia.',
    system: 'Experience System',
    capabilities: ['UX'],
    result: 'Experiencia mejorada.',
    connectedModules: [],
    visualLabel: 'Experience',
    type: 'placeholder',
    title: 'Experience System',
    index: 23,
  },
  'Analytics Portal': {
    problem: 'Portal de analítica.',
    system: 'Analytics Portal',
    capabilities: ['Data'],
    result: 'Acceso a insights.',
    connectedModules: [],
    visualLabel: 'Portal',
    type: 'placeholder',
    title: 'Analytics Portal',
    index: 24,
  },
  'Service Automation': {
    problem: 'Automatización de servicios.',
    system: 'Service Automation',
    capabilities: ['Automatización'],
    result: 'Servicios eficientes.',
    connectedModules: [],
    visualLabel: 'Automation',
    type: 'placeholder',
    title: 'Service Automation',
    index: 25,
  },
  'Data Explorer': {
    problem: 'Exploración de datos.',
    system: 'Data Explorer',
    capabilities: ['Exploración'],
    result: 'Datos accesibles.',
    connectedModules: [],
    visualLabel: 'Explorer',
    type: 'placeholder',
    title: 'Data Explorer',
    index: 26,
  },
  'Operations Console': {
    problem: 'Consola de operaciones.',
    system: 'Operations Console',
    capabilities: ['Operaciones'],
    result: 'Gestión centralizada.',
    connectedModules: [],
    visualLabel: 'Console',
    type: 'placeholder',
    title: 'Operations Console',
    index: 27,
  },
  'System Notes': {
    problem: 'Notas de sistema.',
    system: 'System Notes',
    capabilities: ['Notas'],
    result: 'Documentación rápida.',
    connectedModules: [],
    visualLabel: 'Notes',
    type: 'placeholder',
    title: 'System Notes',
    index: 28,
  },
  'Process': {
    problem: 'Gestión de procesos.',
    system: 'Process',
    capabilities: ['Procesos'],
    result: 'Procesos optimizados.',
    connectedModules: [],
    visualLabel: 'Process',
    type: 'placeholder',
    title: 'Process',
    index: 29,
  },
  'Architecture Method': {
    problem: 'Método de arquitectura.',
    system: 'Architecture Method',
    capabilities: ['Método'],
    result: 'Estandarización.',
    connectedModules: [],
    visualLabel: 'Method',
    type: 'placeholder',
    title: 'Architecture Method',
    index: 30,
  },
  'About': {
    problem: 'Información sobre el sistema.',
    system: 'About',
    capabilities: ['Info'],
    result: 'Contexto claro.',
    connectedModules: [],
    visualLabel: 'About',
    type: 'placeholder',
    title: 'About',
    index: 31,
  },
  'Contact': {
    problem: 'Contacto operativo.',
    system: 'Contact',
    capabilities: ['Contacto'],
    result: 'Comunicación directa.',
    connectedModules: [],
    visualLabel: 'Contact',
    type: 'placeholder',
    title: 'Contact',
    index: 32,
  },
  'module-1': {
    index: '01',
    category: 'Digital Systems Architecture',
    title: 'Systems Reactor',
    type: 'Digital Systems Architecture · Portfolio',
    problem: 'Most digital problems don\'t need more software. They need clearer thinking. Organizations live with chaos not because solutions don\'t exist — but because nobody stopped to imagine what the system should look like if it worked.',
    system: 'This is not a portfolio. It\'s a map of how complex problems become clear systems. Every module here is an answer to the same question: what would this look like if it were designed correctly?',
    capabilities: [
      'Systems imagination & architecture',
      'Modular digital infrastructure',
      'Operational platform design',
      'Data structure & automation',
      'Decision-making systems',
      'Connecting people, processes and data',
    ],
    result: 'Things that organize what was disordered. Systems that make invisible operations visible. Chaos becomes infrastructure.',
    connectedModules: [
      { name: 'SIGA', type: 'Administrative layer' },
      { name: 'SIGO', type: 'Operational layer' },
      { name: 'Analytics Core', type: 'Data infrastructure' },
      { name: 'Automation Layer', type: 'Workflow engine' },
    ],
  },
};
